import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home(props) {
  // Logging to pino-logflare.
  // Will get sent to Logflare via HTTP.

  // Logging with pino.
  // Will appear only in the console of the client.

  return (
    <div className={styles.container}>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Home page</h1>
    </div>
  );
}
